version: '3.8'
services:
  mariadb:
    image: bitnami/mariadb:$MARIADB_TAG
    platform: linux/amd64
    container_name: mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_moodle
    networks:
      - moodle-network
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnami/moodle:$MOODLE_TAG
    platform: linux/amd64
    container_name: moodle
    ports:
      - "$HTTP_PORT:8080"
      - "$HTTPS_PORT:8443"
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=500M
      - PHP_POST_MAX_SIZE=500M
      - PHP_MAX_EXECUTION_TIME=300
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=bitnami
      - MOODLE_DATABASE_NAME=bitnami_moodle
    networks:
      - moodle-network
    volumes:
      - moodle:/bitnami/moodle
      - moodle_data:/bitnami/moodledata

volumes:
  mariadb_data:
    external: true
    name: mariadb_data
  moodle:
    external: true
    name: moodle
  moodle_data:
    external: true
    name: moodle_data

networks:
  moodle-network:
    external: true
    name: moodle-network
